<?php


namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use FOS\UserBundle\Form\Type\RegistrationFormType as BaseRegistrationType;

class RegistrationFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName');
        //   parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function getParent()
    {
        return BaseRegistrationType::class;
        //
        //   return parent::getParent(); // TODO: Change the autogenerated stub
    }


}